# Generated by Django 4.1.4 on 2023-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("color", models.CharField(max_length=7)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("allday", models.BooleanField(default=False)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
