# Generated by Django 4.1.4 on 2023-11-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
