# Generated by Django 4.1.4 on 2023-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("image_url", models.CharField(max_length=300)),
                ("content", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
