# Generated by Django 4.1.4 on 2023-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                ("classroom", models.CharField(max_length=255)),
                ("group_number", models.IntegerField()),
                ("teacher_name", models.CharField(max_length=255)),
                ("class_order", models.IntegerField()),
                ("week_day", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
