# Generated by Django 4.1.4 on 2023-11-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="grade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
