# Generated by Django 4.1.4 on 2023-11-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0002_classroom_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="grade_letter",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
